---
title: "Basque Cakes"
author: "Wen Han Zhao"
---

Welcome to the "Basque Cakes"

Here you will find all the detail on how to make a perfect Basque Cakes!

[**Ingredients**]{.underline}

-   **Flour:** You only need all-purpose (plain) flour\--nothing fancy! Make sure to measure it accurately, preferably with a kitchen scale, for the best results.

-   **Eggs:** They add richness to the cake batter, as well as thickening the pastry cream in conjunction with cornstarch. Use room temperature eggs in the cake for an even mix.

-   **Orange Zest:** This adds a delightful citrus flavor to the pastry cream.

-   **Milk:** You'll need milk for the pastry cream and the cake batter. Be sure to use whole milk for the creamiest result.

STEPS

1.  Combine the **milk and orange zest** in a saucepan, then **bring to a boil** over medium heat.

2.  **Beat** the egg and yolk, flour, cornstarch, sugar, and vanilla *until well combined.*

3.  Gradually **add the milk mixture** to the egg mixture, *whisking constantly,* until it's fully incorporated. (image 3)

4.  Place the pastry cream over medium heat and **whisk until it bubbles and thickens,** about *3-4 minutes.* (image 4)

5.  Pour the pastry cream **through a strainer** to remove any lumps.(image 5)

6.  Combine the **flour and baking powder** in a large bowl. (image 6)

7.  **Beat the butter and sugar** in a separate bowl until smooth and creamy. (image 7)

8.  **Add the eggs one at a time,** beating well in between each addition. (image 8)

9.  Gradually **add the flour mixture** and stir until combined. (image 9)

10. Grease and line a 7-inch cake tin with parchment paper. **Pipe a a spiral of cake batter** on the bottom of the tin, then *pipe a circle around 1 inch (2 cm) up the side.* (image 10)

11. Fill the center of the tin with **the pastry cream,** making sure to level the top. (image 11)

12. **Pipe the remaining batter on top** of the pastry cream. (image 12)

13. *Chill for 15 minutes,* then **brush the top** with an egg yolk and milk mixture. **Drag the tines of a fork across the top** of the cake to make a crosshatched pattern. (image 13)

14. **Bake at 350°F (180°C)** for 45 minutes, then let it cool. Serve on its own or with fruit jam or compote. (image 14)
